name: "Backend"
on:
  push:
    branches: dotnet
jobs:
  clear_container:
    runs-on: self-hosted
    steps:
      - name: clean up
        run: docker stop dotnetwebapi || true && docker rm dotnetwebapi || true
  make_container:
    needs: clear_container
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.3
        with:
          ref: dotnet
      - run: dotnet publish dotnetWebAPI --os linux --arch x64 /t:PublishContainer -c Release
  run_container:
    needs: make_container
    runs-on: self-hosted
    steps:
      - name: start
        run: |
          echo Database={{ secrets.DATABASE }} > config.dn
          echo Key={{ secrets.KEY }} > config.dn
          echo Issuer={{ secrets.ISSUER }} > config.dn
          docker run --ip 172.0.0.1 --name dotnetwebapi -d --env-file config.dn dotnetwebapi
          docker exec -i dotnet bash
          dotnet ef migrations add initial
          echo $Issuer
          exit
