name: "Backend"
on:
  push:
    branches: dotnet
jobs:
  clear_container:
    runs-on: self-hosted
    steps:
      - name: clean up
        run: docker network rm -f mynet
      - run: docker network create --subnet=172.0.0.0/16 mynet
      - run: docker rm -f dotnetwebapi || true
  make_container:
    needs: clear_container
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.3
        with:
          ref: dotnet
      - run: dotnet publish dotnetWebAPI --os linux --arch x64 /t:PublishContainer -c Release
