name: "Setup"
on: 
  push:
    branches: ["dotnet", "django", "frontend"]
jobs:
  setup_nginx:
    runs-on: self-hosted
    steps:
    - name: download nginx
      run: docker image pull nginx:latest
    - name: run nginx
      run: docker run -id nginx:latest -p 80:80
  setup_postgres:
    runs-on: self-hosted
    needs: setup_nginx
    steps:
    - name: download PostgreSQL
      run: docker image pull postgres:latest
    - name: create volume
      run: docker volume create DBVolume
    - name: run PostgreSQL
      run: docker run -id postgres:latest -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -v DBVolume:/var/lib/postgresql/data
      
  
  
    
